/**
 * Docker Compose Template — Generates docker-compose.yml for a company container.
 *
 * Each company gets a single container with:
 * - Resource limits (2 CPU, 2GB RAM by default)
 * - Workspace volume mount at /workspace
 * - MCP server socket mounts from host
 * - Network isolation (dedicated bridge network)
 * - Non-root user execution
 */

import { fileURLToPath } from "url";
import { dirname } from "path";
import type { ContainerConfig, ContainerResources, McpServerName } from "./types.js";
import { MCP_SERVERS } from "./types.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export interface ComposeContext {
  companyId: string;
  companyName: string;
  containerConfig: ContainerConfig;
  mcpServers?: McpServerName[];
  /** Extra environment variables to pass to the container */
  env?: Record<string, string>;
  /** Whether to include the OpenClaw gateway service */
  openclawEnabled?: boolean;
  /** Docker image for OpenClaw (default: ghcr.io/openclaw/openclaw:latest) */
  openclawImage?: string;
}

/**
 * Generate a docker-compose.yml string for a company container.
 */
export function generateComposeFile(ctx: ComposeContext): string {
  const {
    companyId,
    containerConfig,
    mcpServers = [...MCP_SERVERS],
    env = {},
    openclawEnabled = false,
    openclawImage = "ghcr.io/openclaw/openclaw:latest",
  } = ctx;

  const name = `aic-${companyId}`;
  const companyDir = `${containerConfig.companiesDir}/${companyId}`;
  const workspaceHost = `${companyDir}/workspace`;
  const res = containerConfig.resources;

  const volumes = buildVolumes(workspaceHost, containerConfig.mcpServersDir, mcpServers);
  const envLines = buildEnvLines(companyId, env);

  let openclawService = "";
  if (openclawEnabled) {
    openclawService = `
  openclaw-gateway:
    container_name: ${name}-openclaw
    image: ${openclawImage}
    restart: unless-stopped
    volumes:
      - ${companyDir}/.openclaw:/root/.openclaw
      - ${workspaceHost}:/root/workspace
    environment:
      - ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:18789/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          cpus: "${res.cpuLimit}"
          memory: ${res.memoryLimit}
        reservations:
          cpus: "${res.cpuReservation}"
          memory: ${res.memoryReservation}
    networks:
      - ${containerConfig.networkName}
    security_opt:
      - no-new-privileges:true
`;
  }

  return `# Auto-generated by supervisor — do not edit manually
version: "3.8"

services:
  agent:
    container_name: ${name}
    build:
      context: ${__dirname}/../container
      dockerfile: Dockerfile
    restart: unless-stopped
    user: "node"
${envLines}
${volumes}
    deploy:
      resources:
        limits:
          cpus: "${res.cpuLimit}"
          memory: ${res.memoryLimit}
        reservations:
          cpus: "${res.cpuReservation}"
          memory: ${res.memoryReservation}
    networks:
      - ${containerConfig.networkName}
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:size=256m
${openclawService}
networks:
  ${containerConfig.networkName}:
    external: true
`;
}

function buildVolumes(
  workspaceHost: string,
  mcpServersDir: string,
  mcpServers: McpServerName[],
): string {
  const lines = [`      - ${workspaceHost}:/workspace`];

  for (const server of mcpServers) {
    lines.push(
      `      - ${mcpServersDir}/${server}:/mcp/${server}:ro`,
    );
  }

  return `    volumes:\n${lines.join("\n")}`;
}

function buildEnvLines(
  companyId: string,
  extra: Record<string, string>,
): string {
  const envVars: Record<string, string> = {
    COMPANY_ID: companyId,
    NODE_ENV: "production",
    ...extra,
  };

  const lines = Object.entries(envVars).map(
    ([key, value]) => `      - ${key}=${value}`,
  );

  return `    environment:\n${lines.join("\n")}`;
}

/**
 * Get the container name for a company.
 */
export function containerName(companyId: string): string {
  return `aic-${companyId}`;
}
