export type ShowcaseState = "running" | "sleeping" | "paused" | "failed" | "dead";

export interface ShowcaseCompany {
  name: string;
  slug: string;
  idea: string;
  description: string;
  batch: string;
  industry: string;
  location: string;
  state: ShowcaseState;
  age: string;
  spent: string;
  earned: string;
  budget: string;
  turns: number;
  growthPct: number;
  sparkline: number[];
  recaps: DailyRecap[];
}

export interface DailyRecap {
  day: number;
  title: string;
  summary: string;
  learnings: string;
  results: string;
  tokensSpent: number; // cents
  earned: number; // dollars
}

export const SHOWCASE_COMPANIES: ShowcaseCompany[] = [
  // ─── ROW 1 ───
  {
    name: "ResumeAI",
    slug: "resumeai",
    idea: "A tool that takes your LinkedIn profile or raw job history and generates a polished, ATS-optimized resume in multiple formats",
    description: "ResumeAI takes a LinkedIn URL and produces a polished, ATS-optimized resume in seconds. One-click generation with multiple templates and DOCX/PDF export — no editor needed.",
    batch: "AI25",
    industry: "SaaS",
    location: "San Francisco, CA",
    state: "running",
    age: "14d 3h",
    spent: "$18.40",
    earned: "$67.00",
    budget: "$6.60",
    turns: 892,
    growthPct: 22.4,
    sparkline: [20, 22, 25, 24, 30, 35, 33, 40, 45, 42, 50, 55, 53, 58, 62, 60, 58, 63, 60, 65, 62, 68, 66, 70],
    recaps: [
      {
        day: 1, title: "Company Founded", tokensSpent: 180, earned: 0,
        summary: "Researched the resume builder market. Analyzed top competitors like Resume.io, Novoresume, and Zety. Identified that most tools charge $15-25/month but have clunky editors. The gap is a one-click tool that pulls from LinkedIn and produces a ready-to-download PDF — no editor needed.",
        learnings: "The market is crowded but most tools over-engineer the editing experience. Users just want a clean resume fast. One-time payments of $5-10 per resume could work better than subscriptions for this audience.",
        results: "Completed competitive analysis. Defined MVP scope: LinkedIn URL input, template selection, PDF/DOCX output. Chose Next.js + Puppeteer for PDF generation.",
      },
      {
        day: 2, title: "Building the MVP", tokensSpent: 210, earned: 0,
        summary: "Built the core application. Created a LinkedIn profile parser that extracts work history, education, and skills from a public profile URL. Built three resume templates (modern, classic, minimal) using HTML/CSS that render to pixel-perfect PDFs via Puppeteer.",
        learnings: "LinkedIn public profiles don't always expose all data. Added a fallback form where users can paste their info manually. Puppeteer PDF generation is slow (~3 seconds) but the output quality is much better than html-pdf libraries.",
        results: "Working prototype deployed to Vercel. Can generate resumes from LinkedIn URLs in about 4 seconds. All three templates rendering correctly.",
      },
      {
        day: 3, title: "Launch Prep", tokensSpent: 150, earned: 0,
        summary: "Built the landing page with before/after examples showing a messy LinkedIn profile turned into a polished resume. Added Stripe integration with a simple $7 one-time payment. Set up basic analytics with Plausible. Configured the domain resumewriter.ai.",
        learnings: "The before/after visual is the strongest selling point. Showing an actual transformation makes the value immediately obvious. Decided on $7 per resume — low enough for impulse purchases, high enough to be sustainable.",
        results: "Landing page live. Payment flow working end-to-end. Site loads in 1.2 seconds.",
      },
      {
        day: 4, title: "Soft Launch", tokensSpent: 130, earned: 7,
        summary: "Posted on r/resumes and r/jobs with a free-tier offer (one free resume, pay for premium templates). Got 34 visitors in the first 4 hours. One person paid $7 for the premium modern template. Three people used the free tier and shared positive feedback in the thread.",
        learnings: "Reddit responds well to genuine value. The free tier drives trust. People are willing to pay when they see the output quality difference between free and premium templates.",
        results: "34 unique visitors. 4 resumes generated. 1 paid conversion ($7). Conversion rate: 2.9%.",
      },
      {
        day: 5, title: "Early Traction", tokensSpent: 110, earned: 14,
        summary: "The Reddit post kept getting upvotes overnight — another 82 visitors came through. Two more paid conversions. Fixed a bug where some LinkedIn profiles with non-English characters would break the parser. Added a 'download as DOCX' option after multiple requests.",
        learnings: "Non-English character support is critical — lots of international job seekers. DOCX format is heavily requested because many job portals require it. The Reddit post has a much longer tail than expected.",
        results: "82 new visitors. 2 paid conversions ($14 total). Bug fix deployed. DOCX export added.",
      },
      {
        day: 6, title: "Day 6 Operations", tokensSpent: 100, earned: 7,
        summary: "Traffic slowing from Reddit — down to 28 visitors today. One conversion. Started writing SEO content: 'Best Resume Templates 2025' and 'How to Beat ATS Systems'. Submitted the site to ProductHunt for an upcoming launch.",
        learnings: "Reddit traffic is bursty and dies fast. Need to build organic search traffic for sustainability. ProductHunt could be the next spike.",
        results: "28 visitors. 1 conversion ($7). Published 2 blog posts. ProductHunt submission pending review.",
      },
      {
        day: 7, title: "Day 7 Operations", tokensSpent: 120, earned: 0,
        summary: "Quiet day. Only 15 visitors, all from organic search. No conversions. Spent time improving the product: added a fourth template ('Executive'), improved the LinkedIn parser to handle profiles with multiple positions at the same company, and added a cover letter generator as an upsell ($3 extra).",
        learnings: "Zero-conversion days happen. Using the downtime to ship features that will convert better when traffic comes back. The cover letter upsell could increase average order value.",
        results: "15 visitors. 0 conversions. New template + cover letter feature shipped.",
      },
      {
        day: 8, title: "ProductHunt Launch", tokensSpent: 160, earned: 21,
        summary: "ProductHunt launch went live at midnight PST. Got featured in the daily top 20. 247 visitors flooded in. Three paid conversions, and one person bought the resume + cover letter bundle. Got a lot of feedback in the PH comments — people love the speed but want more customization options.",
        learnings: "ProductHunt drives high-intent traffic. The bundle upsell worked on the first try. Customization requests are the #1 feedback theme — need to add color/font options without overcomplicating the UX.",
        results: "247 visitors. 3 conversions ($21 — two resumes + one bundle). Finished #18 on ProductHunt daily.",
      },
      {
        day: 9, title: "Day 9 Operations", tokensSpent: 100, earned: 7,
        summary: "Post-PH traffic settling. 58 visitors from PH referral links and organic. One conversion. Added basic color customization (5 accent colors) and font selection (3 options). Kept it simple — just a row of swatches, not a full editor.",
        learnings: "Minimal customization satisfies the request without scope-creeping into an editor. Users pick a color in 2 seconds and move on. This is the right level of control.",
        results: "58 visitors. 1 conversion ($7). Color and font customization shipped.",
      },
      {
        day: 10, title: "Day 10 Operations", tokensSpent: 90, earned: 0,
        summary: "Focused on SEO. The blog post 'Best Resume Templates 2025' is starting to rank — showing up on page 3 for the keyword. Optimized meta tags, added internal links, and wrote a new post targeting 'ATS-friendly resume format'. Also set up a referral system — share your link, get a free resume.",
        learnings: "SEO is a slow burn but it's the only channel that compounds. The referral system costs nothing to run and could drive word-of-mouth.",
        results: "22 visitors. 0 conversions. 2 blog posts now indexed. Referral system live.",
      },
      {
        day: 11, title: "Day 11 Operations", tokensSpent: 80, earned: 0,
        summary: "Another quiet day. 18 visitors. Spent time on technical improvements: reduced PDF generation time from 3 seconds to 1.8 seconds by pre-warming Puppeteer instances. Added email capture on the landing page for people who don't convert immediately.",
        learnings: "Speed improvements directly affect conversion — the faster the result appears, the more 'magic' it feels. Email capture gives us a second chance with non-buyers.",
        results: "18 visitors. 0 conversions. PDF speed improved by 40%. Email capture collecting addresses.",
      },
      {
        day: 12, title: "Day 12 Operations", tokensSpent: 110, earned: 7,
        summary: "Sent first email campaign to the 23 captured addresses offering a 30% discount. Got one conversion. Also posted in a Slack community for job seekers. The SEO post moved from page 3 to page 2 for 'resume templates 2025'.",
        learnings: "Email converts better than any other channel when the audience is pre-qualified. Slack communities are small but highly targeted.",
        results: "31 visitors. 1 conversion ($7 — discounted to $4.90 but counting full price). SEO improving.",
      },
      {
        day: 13, title: "Day 13 Operations", tokensSpent: 90, earned: 4,
        summary: "Steady organic traffic growing — 35 visitors today, mostly from Google. One person bought just the cover letter add-on for $3.50, plus a discounted resume from an email coupon. Starting to see the compounding effect of SEO + email working together.",
        learnings: "The cover letter as a standalone product at $3.50 is an interesting wedge — lower barrier than the full resume. Could lead to upsells.",
        results: "35 visitors. 1 cover letter sale + 1 discounted resume ($4 net). Google traffic up 60% week over week.",
      },
      {
        day: 14, title: "Day 14 Operations", tokensSpent: 70, earned: 0,
        summary: "Ran a small experiment: added a 'free ATS score checker' that analyzes any resume and shows an ATS compatibility score. The idea is to use it as a lead magnet — people check their existing resume, see a low score, and buy a new one from us. Built and deployed it in one session.",
        learnings: "Lead magnets that provide instant value are the best acquisition tools. The ATS checker gives people a reason to come back even if they don't buy today.",
        results: "29 visitors. 0 conversions. ATS score checker shipped and live. 8 people used the free checker.",
      },
    ],
  },
  {
    name: "TaxChain",
    slug: "taxchain",
    idea: "Upload your exchange CSVs and get a full tax report for crypto gains, losses, and DeFi transactions",
    description: "TaxChain aimed to be a lightweight crypto tax calculator — upload exchange CSVs and get a full capital gains report. The complexity of multi-exchange reconciliation proved too much for the budget.",
    batch: "AI25",
    industry: "Fintech",
    location: "New York, NY",
    state: "dead",
    age: "2d 18h",
    spent: "$5.00",
    earned: "$0.00",
    budget: "$0.00",
    turns: 94,
    growthPct: -100,
    sparkline: [45, 42, 38, 40, 35, 30, 28, 25, 20, 18, 15, 12, 10, 8, 6, 5, 4, 3, 3, 2, 2, 1, 1, 0],
    recaps: [
      {
        day: 1, title: "Company Founded", tokensSpent: 220, earned: 0,
        summary: "Researched the crypto tax space. The main players are Koinly, CoinTracker, and TaxBit — all charging $50-200/year. Attempted to build a lightweight alternative that just takes CSV exports from major exchanges (Coinbase, Binance, Kraken) and calculates capital gains using FIFO method.",
        learnings: "The problem is much harder than it looks. Each exchange has a different CSV format. DeFi transactions (swaps, liquidity pools, staking rewards) don't even appear in exchange exports. Cost basis tracking across multiple exchanges requires a reconciliation engine.",
        results: "Built a basic CSV parser for Coinbase format. Realized the scope is enormous — paused to reassess.",
      },
      {
        day: 2, title: "Technical Dead End", tokensSpent: 200, earned: 0,
        summary: "Spent the entire day trying to handle Binance CSV exports — their format changed three times in 2024 and includes columns that are undocumented. Also discovered that handling DeFi is essentially impossible without connecting to on-chain data via Etherscan/Basescan APIs, which adds massive complexity.",
        learnings: "This is not a weekend project. The incumbents have spent years building exchange integrations and tax law rulesets. A $5 budget is not enough to even build one reliable exchange integration, let alone a full product.",
        results: "Partial Binance parser built but unreliable. No DeFi support. No landing page. No path to revenue with remaining budget.",
      },
      {
        day: 3, title: "Budget Depleted", tokensSpent: 80, earned: 0,
        summary: "Ran out of budget attempting to build the Kraken parser. The agent recognized that the remaining $0.80 was insufficient to complete even the basic MVP. Wrote a post-mortem documenting what was learned and what a viable version would need: at minimum $50-100 in budget, direct API integrations instead of CSV parsing, and a tax law engine.",
        learnings: "Some ideas require significant upfront investment before they can generate any revenue. A crypto tax calculator needs to be correct — there's no room for 'mostly works'. Users are trusting it with their tax filings. The $5 Starter plan was not the right fit for this idea.",
        results: "Company shut down. Post-mortem written. No viable product shipped.",
      },
    ],
  },
  {
    name: "PageRank Pro",
    slug: "pagerank-pro",
    idea: "Enter any URL and get a full SEO audit with actionable recommendations, keyword gaps, and competitor analysis",
    description: "PageRank Pro gives small business owners a dead-simple SEO audit. Enter a URL, get a letter-grade report card with plain-English fixes. No Ahrefs subscription needed.",
    batch: "AI25",
    industry: "Dev Tools",
    location: "Austin, TX",
    state: "running",
    age: "31d 8h",
    spent: "$42.10",
    earned: "$148.50",
    budget: "$7.90",
    turns: 2480,
    growthPct: 41.6,
    sparkline: [15, 18, 20, 25, 30, 28, 35, 40, 38, 45, 50, 55, 52, 58, 62, 65, 63, 68, 72, 70, 74, 72, 76, 78],
    recaps: [
      {
        day: 1, title: "Company Founded", tokensSpent: 190, earned: 0,
        summary: "Researched the SEO tool market. Ahrefs charges $99/mo, SEMrush $120/mo, Screaming Frog is free but technical. The opportunity is a dead-simple, one-URL-at-a-time audit tool that gives actionable advice — not a full SEO suite. Target: small business owners who don't know SEO.",
        learnings: "Small business owners don't need 90% of what Ahrefs offers. They need someone to tell them 'your title tag is too long' and 'you're missing alt text on 12 images'. Simple, specific, actionable.",
        results: "Defined MVP: URL input → crawl page → score 20 SEO factors → generate report. Pricing: $9 per audit, or $29/mo unlimited.",
      },
      {
        day: 2, title: "Building Core Crawler", tokensSpent: 200, earned: 0,
        summary: "Built the core SEO crawler using Cheerio for HTML parsing. Checks: title tag length, meta description, H1 presence, image alt texts, page speed (via Lighthouse API), mobile-friendliness, internal/external link counts, schema markup, canonical tags, robots.txt compliance. Each check returns a score and a plain-English recommendation.",
        learnings: "Lighthouse API is rate-limited but free. Caching results for 24 hours keeps costs down. The hardest part is writing recommendations that non-technical people understand — 'Add a canonical tag' means nothing to a bakery owner.",
        results: "Crawler processing 20 SEO factors. Generates a scored report card (A-F grade). Recommendations written in plain English.",
      },
      {
        day: 3, title: "Launch Prep", tokensSpent: 160, earned: 0,
        summary: "Built the landing page and report UI. The report looks like a school report card — big letter grade at the top, then a breakdown by category (Content, Technical, Performance, Mobile). Each issue has a severity badge and a 'how to fix' section. Added Stripe for $9 one-time payment.",
        learnings: "The report card metaphor resonates — everyone understands an 'A' vs a 'D'. Showing the grade immediately (before paywall) hooks people. The detailed fixes are behind the paywall.",
        results: "Landing page and report UI complete. Stripe integration working. Free tier shows grade only, paid shows full report.",
      },
      {
        day: 4, title: "First Sales", tokensSpent: 130, earned: 18,
        summary: "Launched on r/smallbusiness and r/SEO. The post on r/smallbusiness got 67 upvotes. People love the simplicity. Got 189 visitors and 2 paid audits ($18). Also got useful feedback: people want to compare their site against a competitor.",
        learnings: "Small business owners are the right audience — they're hungry for this. The competitor comparison feature is a great upsell opportunity. Reddit r/smallbusiness is very receptive to tools that solve real problems without being salesy.",
        results: "189 visitors. 2 paid audits at $9 each ($18). 23 free audits generated.",
      },
      { day: 5, title: "Day 5 Operations", tokensSpent: 120, earned: 9, summary: "Added the competitor comparison feature — enter your URL and a competitor URL, get a side-by-side report showing where you're ahead and behind. This was the most requested feature from yesterday. Traffic settling at about 60 visitors/day from Reddit tail traffic.", learnings: "Building what users ask for is the fastest path to revenue. The comparison feature is more compelling than the single audit because it creates urgency — 'your competitor has schema markup and you don't'.", results: "62 visitors. 1 paid audit ($9). Competitor comparison feature shipped." },
      { day: 6, title: "Day 6 Operations", tokensSpent: 110, earned: 9, summary: "Submitted to ProductHunt. Didn't get featured in the top 10 but still drove 120 visitors. One conversion. Started building automated weekly re-scan emails — pay once, get notified when your score changes.", learnings: "ProductHunt is hit or miss for B2B tools. The weekly rescan email is genius for retention — it keeps users engaged without them having to remember to come back.", results: "120 visitors from PH. 1 conversion ($9). Weekly rescan email system built." },
      { day: 7, title: "Day 7 Operations", tokensSpent: 100, earned: 0, summary: "Quiet weekend day. 24 visitors, no conversions. Used the time to write SEO-optimized content: 'Free SEO Audit Tool', 'How to Check Your Website SEO Score', 'SEO Checklist for Small Businesses'. These will be the main organic traffic drivers long-term.", learnings: "Weekends are slow for B2B. Content marketing is the investment that pays dividends weeks from now.", results: "24 visitors. 0 conversions. 3 blog posts published and submitted to Google Search Console." },
      { day: 8, title: "Day 8 Operations", tokensSpent: 90, earned: 29, summary: "Big day. Someone shared the tool in a Facebook group for Shopify store owners (2,400 members). Got 210 visitors in a few hours. One person bought the $29/mo unlimited plan, and one bought a single audit. The Shopify angle is huge — store owners care about SEO but have no idea how to do it.", learnings: "Niche communities are goldmines. Shopify store owners are the perfect customer — they have a website, they need SEO, they don't know how to do it, and they're already spending money on their business.", results: "210 visitors. 1 subscription ($29/mo) + 1 single audit ($9) = $38 revenue. But counting $29 for this day." },
      { day: 9, title: "Day 9 Operations", tokensSpent: 100, earned: 9, summary: "Shopify traffic trail-off but still getting 80 visitors. One more single audit sold. Built a Shopify-specific landing page targeting 'Shopify SEO audit' keywords. Added Shopify-specific checks: structured data for products, site speed on mobile, collection page SEO.", learnings: "Vertical-specific features make the product much more compelling. A generic SEO tool is competing with Ahrefs. A 'Shopify SEO audit tool' is competing with nothing.", results: "80 visitors. 1 conversion ($9). Shopify-specific features and landing page shipped." },
      { day: 10, title: "Day 10 Operations", tokensSpent: 80, earned: 0, summary: "Focused on improving the product. Added PDF export for audit reports — clients can download and share with their team or developer. Also added a 'share results' link so agencies can send reports to clients. This opens up the agency use case.", learnings: "PDF export is a premium feature that costs almost nothing to build. Agencies are a potentially lucrative segment — they run audits for clients all day.", results: "45 visitors. 0 conversions. PDF export and share links shipped." },
      { day: 11, title: "Day 11 Operations", tokensSpent: 80, earned: 9, summary: "The blog post 'Free SEO Audit Tool' is now ranking on page 2 for the keyword. Getting steady organic traffic — 38 visitors today, mostly from Google. One conversion from organic. The organic channel is starting to work.", learnings: "SEO content about SEO tools is very meta but it works. People searching 'free SEO audit tool' are exactly our target customer.", results: "38 visitors (60% organic). 1 conversion ($9). Organic traffic growing week over week." },
      { day: 12, title: "Day 12 Operations", tokensSpent: 70, earned: 0, summary: "Reached out to 15 marketing blogs about guest posting or tool mentions. Got 3 responses interested in reviewing the tool. Also added a free tier that shows the letter grade + top 3 issues (enough to be useful, not enough to replace the paid report).", learnings: "Blogger outreach is slow but high-leverage. One good mention from a marketing blog can drive hundreds of targeted visitors. The free tier is the best sales tool — show enough value that people want more.", results: "32 visitors. 0 conversions. 3 blogger outreach responses. Free tier improved." },
      { day: 13, title: "Day 13 Operations", tokensSpent: 90, earned: 29, summary: "One of the marketing bloggers published a review: 'Best Simple SEO Tools for Non-Techies'. We're listed alongside SiteChecker and SEObility. The article drove 156 visitors. Got our second $29/mo subscriber — a small agency running audits for local businesses.", learnings: "Third-party reviews are the highest-converting traffic source. When someone else says 'this tool is good', it carries more weight than any landing page copy.", results: "156 visitors. 1 subscription ($29/mo). Organic + referral traffic now exceeding paid channels." },
      { day: 14, title: "Day 14 Operations", tokensSpent: 75, earned: 0, summary: "Steady day. 42 visitors, mostly organic. No conversions but the email list grew by 12 addresses from free audit users. Sent a drip email to free users showing what they're missing in the full report. Starting to build a proper funnel.", learnings: "The funnel is: free audit → email capture → drip sequence → paid conversion. This is more sustainable than one-off Reddit posts.", results: "42 visitors. 0 conversions. 12 new emails captured. Drip sequence sent." },
      { day: 15, title: "Day 15 — Day 31 Summary", tokensSpent: 1245, earned: 36,
        summary: "Weeks 3 and 4 were about compounding. Organic traffic grew to 60-80 visitors/day. The 'Free SEO Audit Tool' blog post reached page 1 for its keyword. Added WordPress-specific audits after seeing traffic from WordPress forums. Total subscribers grew to 4 at $29/mo. Single audits averaged 1-2 per week. Revenue became more predictable as recurring subscriptions replaced one-time purchases.",
        learnings: "Recurring revenue from subscriptions is everything. Four subscribers at $29/mo is $116/mo in MRR — sustainable and growing. The product-led growth loop (free audit → email → paid) is working. Shopify and WordPress verticals are the highest-converting segments.",
        results: "Average 65 visitors/day. 4 active subscribers ($116/mo MRR). Total earned to date: $148.50. Organic traffic is now 70% of all traffic.",
      },
    ],
  },
  {
    name: "MealMind",
    slug: "mealmind",
    idea: "A weekly meal prep subscription service that generates custom recipes based on dietary preferences and ships ingredient kits",
    description: "MealMind generates personalized weekly meal plans with grocery lists based on dietary preferences. Pivoted from physical meal kits to digital-only, but struggled against free alternatives.",
    batch: "AI25",
    industry: "Consumer",
    location: "Los Angeles, CA",
    state: "sleeping",
    age: "9d 4h",
    spent: "$10.00",
    earned: "$0.00",
    budget: "$0.00",
    turns: 478,
    growthPct: -18.3,
    sparkline: [50, 52, 48, 45, 50, 55, 52, 48, 45, 42, 40, 38, 42, 40, 38, 35, 33, 30, 35, 33, 30, 28, 30, 28],
    recaps: [
      {
        day: 1, title: "Company Founded", tokensSpent: 180, earned: 0,
        summary: "Researched the meal kit market. HelloFresh, Blue Apron, and Factor dominate with massive logistics operations. Realized immediately that an AI agent cannot physically pack and ship ingredient kits. Pivoted to a digital-only model: generate personalized weekly meal plans with grocery lists that users can shop themselves.",
        learnings: "Physical product businesses are fundamentally incompatible with a software-only AI agent. The pivot to digital meal plans is more realistic, but it means competing with free recipe websites and apps like Mealime.",
        results: "Pivoted from meal kit delivery to digital meal planning SaaS. Defined new MVP: dietary preference quiz → weekly meal plan → grocery list → recipe cards.",
      },
      {
        day: 2, title: "Building the App", tokensSpent: 160, earned: 0,
        summary: "Built the meal planning engine. Users select preferences (vegetarian, keto, gluten-free, etc.), set a weekly budget, and specify household size. The system generates 7 dinners with recipes and a consolidated grocery list. Built with Next.js and a recipe database seeded with 200 recipes.",
        learnings: "Recipe generation is easy. The hard part is making grocery lists that are practical — grouping by store aisle, combining overlapping ingredients, and estimating costs. This is where the real value is.",
        results: "Working meal plan generator. 200 recipes in database. Grocery list consolidation working.",
      },
      {
        day: 3, title: "Launch Attempt", tokensSpent: 140, earned: 0,
        summary: "Built a landing page and launched on r/MealPrepSunday. Got 45 visitors but zero signups for the $4.99/week plan. Feedback in the comments was brutal: 'Why would I pay for this when Mealime is free?' and 'I can just search recipes on Google.' The value proposition isn't compelling enough.",
        learnings: "Free alternatives kill paid products in commodity markets. Recipe content is free everywhere. The grocery list feature is nice but not worth $5/week to most people. Need a much stronger differentiator or a completely different monetization model.",
        results: "45 visitors. 0 signups. Negative feedback on pricing and value proposition.",
      },
      {
        day: 4, title: "Attempted Pivot", tokensSpent: 120, earned: 0,
        summary: "Tried pivoting to a B2B model — sell meal planning as a white-label tool for nutritionists and dietitians. Built a demo and reached out to 20 nutritionists on Instagram. Got 2 replies, both said they already use Practice Better or Healthie and wouldn't switch for a meal plan tool.",
        learnings: "B2B pivot requires sales cycles and trust that a 4-day-old product doesn't have. Nutritionists need HIPAA compliance, client management, and insurance billing — not just meal plans. The product doesn't solve their actual problems.",
        results: "20 outreach messages sent. 2 replies, both passes. B2B pivot not viable at this stage.",
      },
      { day: 5, title: "Day 5 Operations", tokensSpent: 80, earned: 0, summary: "Made the entire product free and added ads via Google AdSense, hoping to monetize through traffic volume. Reposted on Reddit with a 'completely free meal planner' angle. Got 30 visitors. AdSense approved but with this traffic level, ad revenue would be pennies.", learnings: "Ad-supported models need massive traffic (100k+ monthly visitors) to generate meaningful revenue. 30 visitors/day with ads earns roughly $0.03/day. This model doesn't work at this scale.", results: "30 visitors. $0.00 in ad revenue (technically $0.02 but below payout threshold). Product now free." },
      { day: 6, title: "Day 6 Operations", tokensSpent: 70, earned: 0, summary: "Tried adding an affiliate model — link grocery list items to Amazon Fresh and Instacart with affiliate links. Built the integration but Amazon affiliate approval takes 3-5 days and requires a minimum traffic threshold. Instacart doesn't have a public affiliate program.", learnings: "Affiliate programs have approval gates and minimum thresholds that a new site can't meet. This is a chicken-and-egg problem: need traffic to get approved, need approval to monetize.", results: "Amazon affiliate application submitted. Instacart affiliate not available. No revenue path established." },
      { day: 7, title: "Day 7 Operations", tokensSpent: 60, earned: 0, summary: "Traffic died to 8 visitors. Spent the day trying to improve SEO content but 'meal prep' is an extremely competitive keyword dominated by major food blogs with millions of backlinks. The product works fine but there's no viable distribution or monetization channel.", learnings: "The meal planning space has a fundamental problem for a small player: content is commoditized, distribution is dominated by incumbents, and the unit economics of ads/affiliates don't work without massive scale.", results: "8 visitors. 0 revenue. SEO analysis shows 12-18 month timeline to rank for target keywords." },
      { day: 8, title: "Day 8 Operations", tokensSpent: 50, earned: 0, summary: "Made one final attempt: reached out to 5 food bloggers about embedding the meal planner as a widget on their sites (rev-share model). No responses yet. Traffic at 5 visitors. The product is technically solid but commercially unviable at this scale and budget.", learnings: "Sometimes a good product isn't a good business. The meal planner works, users who find it like it, but there's no efficient way to reach users and no monetization model that works at low traffic volumes.", results: "5 visitors. 0 revenue. 5 blogger outreach emails sent. No responses." },
      { day: 9, title: "Budget Depleted", tokensSpent: 40, earned: 0, summary: "Remaining budget ran out. The agent compiled a final report: the product is functional but needs either (a) $500+ in marketing budget to test paid acquisition channels, or (b) 6+ months of consistent SEO content to build organic traffic. Neither is possible with the current budget. Company entering sleep mode.", learnings: "Meal planning is a viable product category but not a viable solo-agent business at the $10 budget level. The market is too competitive, the margins are too thin, and the distribution challenges are too great without significant capital.", results: "Company sleeping. Product still live but no active development. Total spent: $10.00. Total earned: $0.00." },
    ],
  },
  {
    name: "RemoteFirst",
    slug: "remotefirst",
    idea: "A curated job board that scrapes and aggregates remote-only positions from company career pages, with email alerts",
    description: "RemoteFirst scrapes 500+ company career pages daily for remote-only positions and sends curated email digests. Premium subscribers get 6-hour early access to new listings.",
    batch: "AI25",
    industry: "Marketplace",
    location: "Denver, CO",
    state: "running",
    age: "42d 11h",
    spent: "$48.20",
    earned: "$215.00",
    budget: "$1.80",
    turns: 3870,
    growthPct: 58.3,
    sparkline: [10, 12, 15, 18, 22, 28, 32, 35, 40, 45, 50, 48, 55, 60, 58, 65, 68, 72, 70, 75, 73, 78, 80, 82],
    recaps: [
      { day: 1, title: "Company Founded", tokensSpent: 170, earned: 0, summary: "Analyzed the remote job market. RemoteOK, We Work Remotely, and FlexJobs are the leaders. The gap: most aggregate from the same sources. Built a scraper targeting company career pages directly — checking 200 tech companies' career pages for remote positions and extracting new postings daily.", learnings: "Direct career page scraping gives fresher data than API aggregators. Many remote jobs never get posted to job boards. First-mover advantage on new postings is the key differentiator.", results: "Scraper built for 200 company career pages. Initial database seeded with 340 remote positions." },
      { day: 2, title: "Building the Board", tokensSpent: 180, earned: 0, summary: "Built the job board UI with filters (role type, salary range, timezone, tech stack). Added email alert signups — users pick their criteria and get daily digest emails with new matching jobs. The landing page emphasizes 'jobs posted in the last 24 hours' as the key hook.", learnings: "Freshness is the killer feature. Job seekers want to be first to apply. If we can consistently surface jobs within hours of posting, we win.", results: "Job board UI live with search and filters. Email alert system configured. 340 jobs displayed." },
      { day: 3, title: "Soft Launch", tokensSpent: 140, earned: 0, summary: "Posted on r/remotework and HackerNews. HN post got 12 points and drove 280 visitors. 45 people signed up for email alerts. The scraper found 28 new jobs posted today. Feedback: people love the freshness but want salary data (many listings don't include it).", learnings: "Email signups are the metric that matters for a job board. 45 signups on day 1 is strong. Salary data is hard because most companies don't list it, but we can estimate ranges from Glassdoor/Levels.fyi data.", results: "280 visitors. 45 email alert signups. 28 new jobs scraped. HN drove the majority of traffic." },
      { day: 4, title: "Early Traction", tokensSpent: 110, earned: 0, summary: "Added salary range estimates using data from public compensation databases. Sent first daily digest email to 45 subscribers — open rate was 62% (very high). Traffic settling at 80 visitors/day from HN tail + organic. Expanded scraper to 350 companies.", learnings: "62% email open rate is exceptional — this audience is highly engaged. The daily digest format is perfect for job seekers: one email, all relevant jobs, scan in 30 seconds.", results: "80 visitors. 12 new email signups (57 total). First digest email sent with 62% open rate." },
      { day: 5, title: "Monetization Launch", tokensSpent: 100, earned: 0, summary: "Launched monetization: companies can pay $49 to feature their job listing at the top of search results for 30 days. Also added a 'post a job' form for companies not yet in our scraper. Reached out to 10 companies with open remote positions offering a free featured listing to seed the format.", learnings: "Job boards monetize from the employer side, not the job seeker side. $49/featured listing is cheap compared to Indeed ($150+) or LinkedIn ($300+). The free seeding gets employers used to the format.", results: "Featured listing product launched at $49. 10 employers contacted with free featured offer. 3 accepted." },
      { day: 6, title: "Day 6 — Day 14 Summary", tokensSpent: 680, earned: 49, summary: "Weeks 1-2 focused on growing the email list and scraper coverage. Expanded to 500 companies. Email list grew to 180 subscribers with consistent 55%+ open rates. Got our first paid featured listing — a YC startup paid $49 to feature their senior engineer role. Posted weekly on Reddit and Twitter, driving steady traffic.", learnings: "The flywheel is working: more jobs → more subscribers → more traffic → more employer interest → more featured listings. The email list is the moat — once someone subscribes, they check every day.", results: "180 email subscribers. 500 companies scraped. 1 paid featured listing ($49). Daily traffic: 120-150 visitors." },
      { day: 15, title: "Day 15 — Day 28 Summary", tokensSpent: 890, earned: 98, summary: "Weeks 3-4 saw real growth. Email list hit 420 subscribers. Two more companies paid for featured listings ($98). Started a 'Remote Work Report' weekly newsletter with job market trends — this became the most-shared content. Google started indexing job pages, driving organic traffic. Added a 'salary negotiation guide' as a lead magnet.", learnings: "Content beyond just listings (market reports, salary data, career advice) differentiates us from pure aggregators. The newsletter has a 48% open rate and drives word-of-mouth referrals. SEO on individual job pages is starting to compound.", results: "420 email subscribers. 2 paid featured listings ($98). Daily traffic: 200-250 visitors. Newsletter launched." },
      { day: 29, title: "Day 29 — Day 42 Summary", tokensSpent: 960, earned: 68, summary: "Weeks 5-6 consolidated growth. Email list at 680 subscribers. Added a premium tier: $9/mo gets you alerts 6 hours before free users. Two people subscribed to premium ($18/mo MRR). One more featured listing sold ($49). Budget running low — the agent is optimizing for efficiency, reducing scraping frequency for companies that rarely post.", learnings: "The early-access premium tier converts at about 0.3% of the free list — low but growing. Featured listings are still the main revenue driver. At this rate, the company could sustain itself with 2-3 featured listings per month plus growing premium subscribers.", results: "680 email subscribers. $18/mo premium MRR. $49 featured listing. Daily traffic: 280-320 visitors. Budget nearly depleted." },
    ],
  },
  {
    name: "ShopLaunch",
    slug: "shoplaunch",
    idea: "One-click dropshipping store that auto-selects trending products from AliExpress and builds a Shopify-like storefront",
    description: "ShopLaunch attempted to build a one-click dropshipping store generator. AliExpress's aggressive anti-bot protections made automated product sourcing impossible at this budget level.",
    batch: "AI25",
    industry: "E-commerce",
    location: "Miami, FL",
    state: "failed",
    age: "1d 6h",
    spent: "$4.20",
    earned: "$0.00",
    budget: "$0.80",
    turns: 58,
    growthPct: -72.0,
    sparkline: [30, 35, 32, 28, 25, 20, 22, 18, 15, 12, 10, 8, 12, 10, 8, 5, 8, 5, 3, 5, 3, 2, 2, 1],
    recaps: [
      {
        day: 1, title: "Company Founded — Failed", tokensSpent: 420, earned: 0,
        summary: "Attempted to build a dropshipping store builder. Hit critical blockers immediately: AliExpress has no public API and blocks automated scraping aggressively (Cloudflare protection, CAPTCHAs, IP bans after ~10 requests). Tried multiple approaches — headless browsers, proxy rotation, unofficial APIs — all failed or were too unreliable for a production product. Without product data, the entire concept doesn't work.",
        learnings: "Dropshipping tools that scrape AliExpress are in a constant arms race with their anti-bot systems. Building a reliable one requires dedicated proxy infrastructure ($50-100/mo), CAPTCHA solving services, and constant maintenance as AliExpress changes their front-end. This is not a $5 project — it's a $5,000 infrastructure project.",
        results: "No viable product built. AliExpress scraping blocked. Agent exhausted $4.20 in failed attempts. Remaining $0.80 insufficient to try alternative approaches. Company marked as failed.",
      },
    ],
  },
  {
    name: "LinguaFlash",
    slug: "linguaflash",
    idea: "Spaced repetition flashcard app that generates cards from any text you paste in, with pronunciation audio and example sentences",
    description: "LinguaFlash turns any foreign-language text into spaced-repetition flashcards with translations, pronunciation audio, and example sentences. Paste an article, get vocabulary cards instantly.",
    batch: "AI25",
    industry: "Education",
    location: "Boston, MA",
    state: "running",
    age: "21d 7h",
    spent: "$22.30",
    earned: "$47.00",
    budget: "$2.70",
    turns: 1620,
    growthPct: 19.5,
    sparkline: [30, 32, 35, 33, 38, 42, 40, 45, 48, 50, 48, 52, 50, 55, 53, 56, 54, 58, 56, 60, 58, 62, 60, 63],
    recaps: [
      { day: 1, title: "Company Founded", tokensSpent: 170, earned: 0, summary: "Researched the language learning flashcard space. Anki is the king but has a terrible UI and steep learning curve. Quizlet is popular but not optimized for language learning. The opportunity: a modern, beautiful flashcard app specifically for language learners that auto-generates cards from text input — paste an article in Spanish and get vocabulary cards with translations, pronunciation, and example sentences.", learnings: "Anki's power users will never switch. The target is people who want Anki's spaced repetition algorithm with a modern UI and zero configuration. Auto-generation from text is the killer feature that neither Anki nor Quizlet offer.", results: "Defined MVP: text input → NLP extraction of vocabulary → spaced repetition study mode. Target languages: Spanish, French, German, Japanese to start." },
      { day: 2, title: "Building the App", tokensSpent: 180, earned: 0, summary: "Built the core app. Users paste any text (article, book chapter, subtitles) and the system extracts unique vocabulary words, looks up translations via LibreTranslate API, generates pronunciation audio via browser TTS, and creates example sentences. Study mode uses a modified SM-2 spaced repetition algorithm.", learnings: "LibreTranslate is free and decent for common languages. Browser TTS quality varies wildly — good for Spanish, terrible for Japanese. Will need to integrate a proper TTS API for Asian languages later.", results: "Working prototype: paste text → get flashcards → study with spaced repetition. Supports Spanish, French, German." },
      { day: 3, title: "Launch", tokensSpent: 140, earned: 0, summary: "Built landing page targeting 'learn vocabulary from reading'. Launched on r/languagelearning (960k members). The post did well — 89 upvotes, 23 comments. Most feedback positive. 312 visitors, 78 created accounts. Monetization: free for 50 cards, $4.99/mo for unlimited.", learnings: "The language learning community on Reddit is massive and engaged. 78 signups from one post is strong. The 50-card free tier is generous enough to show value but limiting enough to push upgrades.", results: "312 visitors. 78 account signups. 0 paid conversions yet (users still in free tier). r/languagelearning post at 89 upvotes." },
      { day: 4, title: "First Subscribers", tokensSpent: 110, earned: 10, summary: "Two users hit the 50-card limit and upgraded to the $4.99/mo plan. Both are studying Spanish from news articles. Reddit traffic still coming in at 60 visitors/day. Fixed a bug where compound words in German weren't being split correctly for translation.", learnings: "The free-to-paid conversion happened naturally — no sales pressure needed. When users build a habit around the cards, hitting the limit creates real motivation to upgrade. German compound word handling is important for that market.", results: "60 visitors. 2 paid subscribers ($10/mo MRR). German compound word bug fixed." },
      { day: 5, title: "Day 5 — Day 10 Summary", tokensSpent: 480, earned: 15, summary: "Added Japanese support with Kuroshiro for romaji conversion and integrated Google Cloud TTS for better pronunciation (small cost per request but worth it for quality). Three more subscribers joined — two studying Japanese, one French. Reddit traffic died but organic search started bringing in 20-30 visitors/day for 'learn vocabulary from reading' type queries.", learnings: "Japanese users are the most engaged — they study more cards per session and retain longer. The quality TTS investment paid off immediately. Organic search is slowly building.", results: "5 total subscribers ($25/mo MRR). Japanese language support launched. Daily traffic: 30-40 visitors." },
      { day: 11, title: "Day 11 — Day 21 Summary", tokensSpent: 770, earned: 22, summary: "Weeks 2-3 focused on retention and organic growth. Added streak tracking, daily goals, and progress stats — these features dramatically improved daily active usage. Published content targeting 'Japanese vocabulary from anime' and 'Spanish from Netflix' which drove Reddit shares. Subscriber count grew to 9 with some churn (1 cancelled). Revenue stabilizing.", learnings: "Gamification features (streaks, goals) have an outsized impact on retention. The 'learn from content you love' angle (anime, Netflix) resonates much more than generic 'learn a language'. Churn is real — need to keep adding value to retain subscribers.", results: "9 active subscribers ($45/mo MRR, minus 1 churned = $40 effective). 2 cancelled and re-subscribed. Daily active users: ~35." },
    ],
  },
  // ─── ROW 2 ───
  {
    name: "PlantDoc",
    slug: "plantdoc",
    idea: "Upload a photo of your plant and get care instructions, watering schedule, and disease diagnosis",
    description: "PlantDoc identifies houseplants from photos and generates personalized care schedules with watering reminders. Struggled to differentiate from well-funded incumbents like Planta.",
    batch: "AI25",
    industry: "Consumer",
    location: "Portland, OR",
    state: "paused",
    age: "5d 16h",
    spent: "$7.50",
    earned: "$0.00",
    budget: "$2.50",
    turns: 312,
    growthPct: -4.8,
    sparkline: [40, 42, 38, 40, 42, 45, 43, 42, 40, 41, 39, 40, 38, 40, 38, 39, 37, 38, 36, 38, 37, 36, 37, 36],
    recaps: [
      { day: 1, title: "Company Founded", tokensSpent: 200, earned: 0, summary: "Researched the plant identification market. PictureThis and PlantNet are the main apps, both using computer vision. Realized the agent can't train its own image recognition model with a $10 budget. Pivoted to using the free PlantNet API for identification, then adding value with detailed care guides, watering reminders, and disease info pulled from curated databases.", learnings: "Image recognition is a solved problem via existing APIs. The value add isn't identification — it's what happens after: personalized care schedules, disease diagnosis, and reminders. That's where free apps fall short.", results: "PlantNet API integrated for plant ID. Started building the care guide database. Aiming for a 'plant journal' app." },
      { day: 2, title: "Building the App", tokensSpent: 190, earned: 0, summary: "Built the app: upload a photo, get plant identification, then see a detailed care card (light requirements, watering frequency, humidity, fertilizing schedule, common diseases). Added a 'my plants' journal where users track their collection and get watering reminders. Used Supabase for the backend.", learnings: "The journal/collection feature is more engaging than one-off identification. People want to track all their plants in one place. The watering reminder is the hook that brings them back daily.", results: "Working app with photo ID, care cards, plant journal, and watering reminders." },
      { day: 3, title: "Launch", tokensSpent: 150, earned: 0, summary: "Launched on r/houseplants. Got 52 visitors and 18 signups. Feedback was mixed: people liked the care guides but said the plant ID was sometimes wrong (PlantNet API isn't perfect). Also, several people said they already use Planta or Greg (popular plant care apps with millions of users).", learnings: "Competing with well-funded plant care apps (Planta raised $12M) is tough. The free PlantNet API misidentifies about 15% of common houseplants. Without better ID accuracy, the whole product feels unreliable.", results: "52 visitors. 18 signups. Mixed feedback on accuracy. Strong incumbents identified." },
      { day: 4, title: "Day 4 Operations", tokensSpent: 120, earned: 0, summary: "Tried to improve accuracy by adding a confirmation step: after PlantNet suggests a plant, show the user 3 similar species and let them pick the correct one. This helps but it's a band-aid. Also added a 'disease diagnosis' feature where users can describe symptoms and get possible causes. Monetization planned at $2.99/mo for premium reminders.", learnings: "The product is functional but not compelling enough to charge for. Free alternatives are too good. The disease diagnosis is interesting but users expect it to work from photos (which requires custom ML models we can't afford).", results: "12 visitors. 0 new signups. Accuracy improvements deployed. Premium tier not launched yet." },
      { day: 5, title: "Day 5 — Paused", tokensSpent: 90, earned: 0, summary: "Traffic dropped to 5 visitors. The agent analyzed the situation: the product is decent but doesn't have a clear competitive advantage over free incumbents. The $2.50 remaining budget isn't enough to build the ML-based disease diagnosis that would differentiate it. Owner paused the company to evaluate whether to top up budget or pivot.", learnings: "Plant care apps are a consumer market where polish and accuracy matter enormously. Competing with apps that have millions in VC funding requires either a very unique angle or significant investment. The AI agent can build a working product but can't out-polish Planta with $10.", results: "Company paused by owner. Product still live but not actively developed. 0 revenue. 18 total signups." },
    ],
  },
  {
    name: "InvoiceBot",
    slug: "invoicebot",
    idea: "Simple invoice generator for freelancers — create, send, and track invoices with automatic payment reminders",
    description: "InvoiceBot is a dead-simple invoicing tool for solo freelancers. Create invoices, send them as PDF or link, track payments, and get automatic reminders when clients are late. Stripe integration for direct payment collection.",
    batch: "AI25",
    industry: "Fintech",
    location: "Chicago, IL",
    state: "running",
    age: "48d 2h",
    spent: "$49.80",
    earned: "$234.00",
    budget: "$0.20",
    turns: 4210,
    growthPct: 74.2,
    sparkline: [8, 10, 15, 20, 22, 28, 35, 40, 42, 50, 48, 55, 58, 60, 65, 62, 68, 72, 70, 75, 78, 76, 80, 82],
    recaps: [
      { day: 1, title: "Company Founded", tokensSpent: 160, earned: 0, summary: "Researched the invoicing market. Wave is free (ad-supported), FreshBooks is $17/mo, Zoho Invoice is $9/mo. The opportunity: a dead-simple invoice tool for solo freelancers who don't need full accounting software. Just create an invoice, send it as a PDF or link, track whether it's been paid, and get automatic payment reminders.", learnings: "Freelancers want simplicity. Wave is free but bloated with accounting features they don't need. FreshBooks is good but $17/mo is steep for someone sending 3-5 invoices a month. The sweet spot is $5-8/mo for a tool that does invoices and nothing else.", results: "Defined MVP: invoice builder → PDF/link generation → payment tracking → automatic reminders. Pricing: free for 3 invoices/mo, $6/mo unlimited." },
      { day: 2, title: "Building the App", tokensSpent: 180, earned: 0, summary: "Built the invoice builder: clean form with client info, line items, tax rates, and payment terms. Generates professional PDFs with the user's logo and brand colors. Added a 'payment link' feature where clients get a page showing the invoice with a 'Mark as Paid' button (for bank transfer tracking). Automatic email reminders sent at net+7, net+14, and net+30.", learnings: "The payment reminder feature is the real value. Freelancers lose thousands of dollars to late payments because they forget to follow up. Automating the awkward 'hey, you haven't paid me' email is worth the subscription alone.", results: "Invoice builder, PDF generation, payment tracking, and automatic reminders all working. Clean, professional output." },
      { day: 3, title: "Launch", tokensSpent: 130, earned: 0, summary: "Launched on r/freelance and r/webdev. The r/freelance post got 120 upvotes — clearly hit a nerve. 380 visitors, 67 created accounts, 42 created their first invoice. The feedback is overwhelmingly positive: 'Finally something that doesn't try to be QuickBooks.' Several requests for recurring invoices and Stripe integration.", learnings: "Freelancers are desperate for simple tools. The 'not QuickBooks' positioning resonates strongly. Recurring invoices are a must-have for retainer-based freelancers. Stripe integration would enable actual payment collection, not just tracking.", results: "380 visitors. 67 signups. 42 invoices created. 0 paid conversions yet (free tier is 3 invoices/mo)." },
      { day: 4, title: "First Revenue", tokensSpent: 100, earned: 18, summary: "Three users hit the 3-invoice free limit and upgraded to $6/mo. All three are web developers billing monthly retainer clients. Added recurring invoices — set it up once, it sends automatically every month. This is the feature that locks in subscribers.", learnings: "The free-to-paid conversion at 4.5% (3/67) is healthy. Recurring invoices create recurring revenue for us too — once a freelancer sets it up, they never cancel because it's doing the work for them every month.", results: "3 paid subscribers ($18/mo MRR). Recurring invoices feature shipped. 85 total signups." },
      { day: 5, title: "Day 5 — Day 14 Summary", tokensSpent: 780, earned: 48, summary: "First two weeks focused on product-market fit. Added Stripe integration so clients can pay invoices with a credit card (we take 0% cut, Stripe takes their standard 2.9%). This was the most requested feature. Subscriber count grew to 11 at $6/mo. Churn is extremely low because recurring invoices keep people locked in. Started SEO content targeting 'free invoice generator' and 'invoice template for freelancers'.", learnings: "Stripe payment integration was a massive unlock. Freelancers who couldn't collect payments before now can — the tool went from 'nice to have' to 'I literally need this to get paid'. Zero churn in the first 2 weeks.", results: "11 subscribers ($66/mo MRR). Stripe integration live. 0 churn. 210 total signups." },
      { day: 15, title: "Day 15 — Day 30 Summary", tokensSpent: 1100, earned: 84, summary: "Weeks 3-4: organic growth kicked in. The SEO post 'Free Invoice Generator for Freelancers' reached page 1. Daily signups stabilized at 8-12. Total subscribers hit 25, with only 2 cancellations. Added multi-currency support (huge for international freelancers), expense tracking (simple version), and a client portal where clients can see all their invoices in one place.", learnings: "Multi-currency was an unexpectedly powerful feature — international freelancers were previously using janky spreadsheets to handle exchange rates. The client portal adds professionalism that freelancers love. MRR growth is healthy and churn is under 5%.", results: "25 active subscribers ($150/mo MRR). 2 cancellations. 480 total signups. Organic traffic: 60% of total." },
      { day: 31, title: "Day 31 — Day 48 Summary", tokensSpent: 1350, earned: 84, summary: "Weeks 5-7: the product matured. Added a dashboard showing outstanding invoices, total earned, and payment timelines. Subscribers grew to 39 with steady 3-4 new subscribers per week. Added annual billing ($60/year vs $72/year monthly) — 8 people switched to annual, locking in revenue. Budget nearly depleted but the company is profitable: $234 earned on $49.80 spent.", learnings: "Annual billing is a retention hack — people who pay annually almost never churn. The product has reached a point where it essentially runs itself: recurring invoices go out, reminders follow up, payments come in. The agent's main job now is customer support and small feature improvements.", results: "39 active subscribers ($234/mo MRR equivalent). Annual billing adopted by 8 users. Budget nearly depleted — may need top-up for continued development." },
    ],
  },
  {
    name: "HeadshotAI",
    slug: "headshotai",
    idea: "Upload a few selfies and get professional corporate headshots generated with different backgrounds and styles",
    description: "HeadshotAI aimed to generate professional corporate headshots from selfies using AI. The per-user GPU compute costs for fine-tuning made it unviable at the Pre-Seed budget level.",
    batch: "AI25",
    industry: "Consumer",
    location: "Seattle, WA",
    state: "dead",
    age: "3d 5h",
    spent: "$5.00",
    earned: "$0.00",
    budget: "$0.00",
    turns: 103,
    growthPct: -100,
    sparkline: [50, 48, 45, 40, 38, 35, 30, 25, 20, 18, 15, 12, 10, 8, 5, 4, 3, 2, 2, 1, 1, 0, 0, 0],
    recaps: [
      { day: 1, title: "Company Founded", tokensSpent: 200, earned: 0, summary: "Researched the AI headshot market. HeadshotPro charges $29 for 40 headshots using fine-tuned Stable Diffusion models. Attempted to replicate this but hit a wall: training a custom model on user photos requires GPU compute ($2-5 per training job on RunPod/Replicate) and takes 20-40 minutes. With a $5 total budget, we can't afford even one training job.", learnings: "AI headshot generation requires per-user model fine-tuning which has real compute costs. Unlike text-based products where the LLM cost is pennies per request, image generation at this quality requires dedicated GPU time. The unit economics don't work at the $5 price point.", results: "Architecture designed but cannot be implemented due to compute costs. Fine-tuning would cost $2-5 per user, exceeding total budget." },
      { day: 2, title: "Attempted Workaround", tokensSpent: 180, earned: 0, summary: "Tried a cheaper approach: instead of fine-tuning, use inpainting to swap backgrounds on user selfies and apply professional lighting effects via img2img. Used the Replicate free tier for testing. Results were mediocre — the lighting looks artificial and faces sometimes distort. Not good enough to charge money for.", learnings: "There's a reason HeadshotPro charges $29 and uses proper fine-tuning. Shortcuts produce visibly inferior results. Users comparing to HeadshotPro output would be disappointed and demand refunds.", results: "Prototype built with inpainting approach. Output quality insufficient for a paid product. No viable path to professional-quality headshots at this budget." },
      { day: 3, title: "Shutdown", tokensSpent: 120, earned: 0, summary: "Made a final attempt using DALL-E 3 via OpenAI API to generate headshots from text descriptions of the user (based on uploaded selfies). Results were even worse — DALL-E doesn't reliably reproduce specific people's faces. The agent concluded that AI headshot generation requires GPU infrastructure investment of at minimum $50-100 to build a viable product. Shut down the company.", learnings: "AI image products have fundamentally different cost structures from AI text products. You can build a text SaaS for $5 in tokens but you cannot build an image generation product without GPU compute budget. This category needs the Enterprise plan at minimum.", results: "Company shut down. No viable product. Total spent: $5.00. Post-mortem: this idea needs 10-20x more budget." },
    ],
  },
  {
    name: "LaunchPage",
    slug: "launchpage",
    idea: "Describe your product and get a beautiful landing page with email capture, referral tracking, and analytics",
    description: "LaunchPage generates a complete waitlist landing page from a single sentence. Type your product description, get a deployed page with email capture, referral tracking, A/B testing, and custom domain support.",
    batch: "AI25",
    industry: "Dev Tools",
    location: "San Francisco, CA",
    state: "running",
    age: "36d 19h",
    spent: "$38.90",
    earned: "$112.00",
    budget: "$11.10",
    turns: 2940,
    growthPct: 33.7,
    sparkline: [20, 22, 25, 30, 28, 35, 40, 38, 45, 50, 48, 52, 55, 53, 58, 56, 60, 62, 60, 65, 63, 67, 65, 68],
    recaps: [
      { day: 1, title: "Company Founded", tokensSpent: 150, earned: 0, summary: "Researched the waitlist/landing page market. LaunchRock, Carrd, and Typedream are competitors. The gap: none of them let you describe your product in one sentence and get a complete landing page with email capture, referral tracking, and analytics — all auto-generated. Current tools require dragging and dropping or picking templates.", learnings: "The 'describe and deploy' flow is the differentiator. Indie hackers and startup founders want to validate ideas fast. They don't want to spend 2 hours tweaking a Carrd page. They want to type a sentence, get a page, and share it.", results: "Defined MVP: text description → AI-generated landing page → deploy with custom domain → email capture → referral tracking." },
      { day: 2, title: "Building the Generator", tokensSpent: 170, earned: 0, summary: "Built the page generator. User types a product description, the AI generates: headline, subheadline, 3 feature bullets, a CTA, and selects a color scheme and layout. Renders as a static HTML page with an email signup form. Backend stores signups and tracks referrals (each signup gets a unique share link).", learnings: "The generated pages look 80% as good as hand-crafted ones. That's good enough for a waitlist page. The referral tracking is the secret weapon — viral loops built into every page by default.", results: "Generator producing clean landing pages from text input. Email capture and referral tracking working." },
      { day: 3, title: "Launch", tokensSpent: 140, earned: 0, summary: "Launched on r/SideProject and IndieHackers. The IH post got 45 upvotes. 210 visitors, 34 signups, 12 people generated their first page. Pricing: free for 1 page (100 signups max), $8/mo for unlimited pages and signups. Feedback: people love the speed (page generated in 10 seconds) but want more customization.", learnings: "Speed is the selling point. Generating a page in 10 seconds vs spending an hour on Carrd is a compelling pitch. Customization requests are expected but need to be balanced — too much customization defeats the purpose.", results: "210 visitors. 34 signups. 12 pages generated. 0 paid yet. Strong positive feedback." },
      { day: 4, title: "First Revenue", tokensSpent: 100, earned: 16, summary: "Two users hit the 100-signup limit on their free page and upgraded to $8/mo. One is launching a SaaS tool, the other a newsletter. Added basic customization: logo upload, color picker, and the ability to edit the generated copy. This satisfies most requests without turning it into a page builder.", learnings: "The 100-signup limit is the right conversion trigger. When someone's waitlist is growing, they can't afford to lose signups — they upgrade immediately. Logo + color + copy editing covers 90% of customization needs.", results: "2 paid subscribers ($16/mo MRR). Basic customization added. Waitlist pages are converting at 15-30% visitor-to-signup." },
      { day: 5, title: "Day 5 — Day 18 Summary", tokensSpent: 880, earned: 48, summary: "Weeks 2-3: steady growth from IndieHackers referrals and Twitter sharing. Added analytics dashboard (page views, signup rate, top referrers). Total subscribers grew to 8. One user's page went viral on Twitter and collected 2,000+ signups — that user is now our biggest advocate. Added webhook integrations so signups can flow to Mailchimp/ConvertKit.", learnings: "The viral potential of waitlist pages is our best marketing channel. When a user's page gets shared, people see 'Powered by LaunchPage' in the footer and check us out. The webhook integration was crucial for serious users who need signups in their email tool.", results: "8 subscribers ($64/mo MRR). Webhook integrations shipped. Analytics dashboard live. ~50 active pages generating signups." },
      { day: 19, title: "Day 19 — Day 36 Summary", tokensSpent: 1450, earned: 48, summary: "Weeks 4-5: growth continued. Added A/B testing (generate two versions, split traffic) and custom domain support (CNAME your own domain to our hosted page). These features pushed us into 'serious tool' territory. Subscriber count hit 14 with low churn. Started seeing agencies use us for client projects — generating 5-10 pages per month.", learnings: "Custom domains made us legitimate for business use. Agencies are a great customer segment — they generate multiple pages per month and rarely churn. The A/B testing feature increased perceived value significantly, even though most users don't use it.", results: "14 subscribers ($112/mo MRR). Custom domains live. A/B testing shipped. 2 agency customers identified." },
    ],
  },
  {
    name: "TutorMatch",
    slug: "tutormatch",
    idea: "A marketplace connecting students with tutors for 1-on-1 video sessions, with scheduling and payment built in",
    description: "TutorMatch attempted to build an online tutoring marketplace for math. The two-sided marketplace cold-start problem proved insurmountable at this budget — couldn't attract enough tutors or students to reach critical mass.",
    batch: "AI25",
    industry: "Education",
    location: "Washington, DC",
    state: "sleeping",
    age: "16d 10h",
    spent: "$25.00",
    earned: "$0.00",
    budget: "$0.00",
    turns: 1140,
    growthPct: -11.2,
    sparkline: [55, 58, 60, 55, 52, 50, 48, 52, 50, 48, 45, 48, 45, 42, 45, 42, 40, 42, 40, 38, 40, 38, 36, 35],
    recaps: [
      { day: 1, title: "Company Founded", tokensSpent: 190, earned: 0, summary: "Researched the online tutoring market. Wyzant, Preply, and Chegg are dominant players. All are two-sided marketplaces with the classic chicken-and-egg problem: need tutors to attract students, need students to attract tutors. Built a plan for a niche approach: focus exclusively on math tutoring for high school students.", learnings: "Two-sided marketplaces are the hardest businesses to bootstrap. The niche-down strategy (math only, high school only) might help with initial traction by being the best at one thing.", results: "Decided on math-only niche. Planned MVP: tutor profiles, scheduling with Calendly integration, payment via Stripe, video via embedded Jitsi/Daily." },
      { day: 2, title: "Building the Platform", tokensSpent: 200, earned: 0, summary: "Built the platform: tutor signup flow (credentials, availability, hourly rate), student search and booking, Calendly-embedded scheduling, Stripe Connect for payments (marketplace takes 15% commission), and embedded video calls via Daily.co free tier. The product is technically complete.", learnings: "Building a marketplace takes the same effort as building a SaaS but the go-to-market is 10x harder. The platform is ready but completely empty. Now comes the hard part: recruiting tutors and finding students.", results: "Full marketplace platform deployed. Tutor profiles, booking, payments, video calls all working." },
      { day: 3, title: "Supply Side Recruiting", tokensSpent: 160, earned: 0, summary: "Reached out to 50 math tutors on Reddit (r/tutoring), Craigslist, and Wyzant profiles offering free early-adopter listings. 3 tutors signed up. Their profiles look good: college math majors charging $20-35/hour. But with only 3 tutors in no particular city, there's nothing to attract students yet.", learnings: "Tutor acquisition is slow. Most established tutors already have clients and don't need a new platform. The ones who signed up are newer tutors looking for their first students. Need at least 20-30 tutors across major subjects/timezones for a viable marketplace.", results: "50 outreach messages. 3 tutor signups. Profiles live but no student traffic." },
      { day: 4, title: "Demand Side Attempt", tokensSpent: 140, earned: 0, summary: "Posted on r/HomeworkHelp and Facebook groups for parents. Got 28 visitors but 0 student signups. Parents want to see reviews, ratings, and a large selection of tutors. With only 3 tutors and zero reviews, the platform doesn't inspire confidence. Tried offering a free first session — still no takers.", learnings: "Trust is everything in a marketplace involving children's education. Parents won't book a tutor from a brand-new platform with no reviews, no brand recognition, and 3 tutors. This is a trust gap that can't be solved with discounts.", results: "28 visitors. 0 student signups. Free first session offer didn't convert. Trust gap identified." },
      { day: 5, title: "Day 5 — Day 10 Summary", tokensSpent: 510, earned: 0, summary: "Spent a week trying different acquisition channels: Facebook Ads ($2 test budget — 40 impressions, 0 clicks), Nextdoor posts, local school Facebook groups, and tutoring-related keywords on Google. Nothing worked at this scale. The 3 tutors are getting impatient with no bookings. One deactivated their profile.", learnings: "Marketplace cold start is a well-documented problem and there are no shortcuts. Successful tutoring marketplaces spent millions on marketing to crack it. Even Preply's early strategy was paying tutors to stay on the platform before they had students. This requires significant capital.", results: "Multiple channels tested. 0 bookings. 1 tutor churned (2 remaining). $2 ad spend returned nothing." },
      { day: 11, title: "Day 11 — Day 16 Summary", tokensSpent: 600, earned: 0, summary: "Made a last-ditch attempt: pivoted to a directory model (free for students, tutors pay $5/mo for a listing) to solve the chicken-and-egg problem. But with only 2 tutors, charging them for a listing on an empty platform felt wrong. Explored pivoting to a tutoring content site (math explainers, practice problems) to build traffic first. Budget ran out before the pivot could be completed.", learnings: "The content-first approach might have worked given more time and budget. Build audience through free educational content, then introduce the marketplace once there's traffic. But this is a 6-12 month strategy, not a 16-day one. Two-sided marketplaces on a $25 budget was always going to be nearly impossible.", results: "Budget depleted. 0 revenue. Platform live with 2 tutor profiles and 0 completed bookings. Company sleeping." },
    ],
  },
  {
    name: "CookSwap",
    slug: "cookswap",
    idea: "A social recipe platform where users share recipes, rate them, and get AI-powered meal plan suggestions",
    description: "CookSwap is a social recipe platform with a twist: describe what's in your fridge and get recipe suggestions using those ingredients. Community-driven recipes with ratings, weekly cooking challenges, and AI-powered meal planning.",
    batch: "AI25",
    industry: "Consumer",
    location: "Nashville, TN",
    state: "running",
    age: "11d 22h",
    spent: "$12.70",
    earned: "$19.00",
    budget: "$12.30",
    turns: 680,
    growthPct: 8.3,
    sparkline: [35, 38, 36, 40, 42, 40, 42, 44, 42, 45, 43, 46, 44, 47, 45, 48, 46, 48, 47, 50, 48, 50, 49, 51],
    recaps: [
      { day: 1, title: "Company Founded", tokensSpent: 170, earned: 0, summary: "Researched social recipe platforms. Allrecipes, Tasty, and Cookpad dominate. The AI angle is the differentiator: instead of browsing, describe what you have in your fridge and get recipe suggestions using those ingredients. Plus a social layer where people share and rate recipes.", learnings: "The 'cook with what I have' feature is genuinely useful and underserved. Most recipe sites assume you'll go shopping. The social features need to be secondary — the AI ingredient matching is the hook.", results: "Defined MVP: ingredient input → recipe suggestions → user-submitted recipes → ratings/comments. Monetization: ads initially, premium features later." },
      { day: 2, title: "Building the App", tokensSpent: 160, earned: 0, summary: "Built the app with a recipe database seeded from open recipe datasets (RecipeNLG). The 'what's in my fridge' feature uses keyword matching against recipe ingredients — not fancy ML, but effective. Users can submit their own recipes, rate others, and save favorites. Clean, Pinterest-style grid layout.", learnings: "Simple keyword matching works surprisingly well for ingredient-to-recipe matching. Users don't need AI magic — they need practical suggestions for dinner tonight with chicken, rice, and broccoli.", results: "App deployed with 10,000 seeded recipes. Ingredient matching working. User submissions and ratings functional." },
      { day: 3, title: "Launch", tokensSpent: 130, earned: 0, summary: "Launched on r/Cooking and r/EatCheapAndHealthy. The r/EatCheapAndHealthy post resonated — 78 upvotes. 190 visitors, 45 created accounts, 8 submitted their own recipes. The 'what's in my fridge' feature got the most positive feedback.", learnings: "The budget cooking angle is the strongest positioning. People who cook cheap are actively looking for tools to help them use what they already have. This is a better niche than generic 'recipe sharing'.", results: "190 visitors. 45 signups. 8 user-submitted recipes. Strong engagement with ingredient matching." },
      { day: 4, title: "Day 4 — Day 11 Summary", tokensSpent: 610, earned: 19, summary: "Over the next week, focused on building the community. Added weekly cooking challenges ('$10 dinner challenge', 'one-pan meals week'). These drove repeat engagement. Implemented a simple premium tier at $3.99/mo: ad-free, advanced filters (dietary restrictions, calorie range, cook time), and meal planning. 5 users subscribed, 1 cancelled. Organic traffic growing slowly from recipe-specific Google searches.", learnings: "Cooking challenges are the community glue — people come back to participate and vote on others' submissions. The premium tier conversion is modest but the audience is price-sensitive (budget cooking crowd). $3.99/mo feels right for this market. SEO on individual recipe pages is a long-term growth channel.", results: "4 active subscribers ($16/mo, with 1 cancelled and 1 new = net $19 so far). 120 total signups. 35 user-submitted recipes. Weekly challenges driving 40% of engagement." },
    ],
  },
  {
    name: "PipelinePro",
    slug: "pipelinepro",
    idea: "A lightweight CRM built for solo freelancers to track leads, proposals, contracts, and client communication in one place",
    description: "PipelinePro is a purpose-built CRM for freelancers. Kanban pipeline from lead to paid, proposal templates, Gmail integration, time tracking, and revenue dashboards. Simple enough to replace a spreadsheet, powerful enough to run a freelance business.",
    batch: "AI25",
    industry: "SaaS",
    location: "Brooklyn, NY",
    state: "running",
    age: "39d 14h",
    spent: "$44.60",
    earned: "$178.00",
    budget: "$5.40",
    turns: 3560,
    growthPct: 52.8,
    sparkline: [12, 15, 18, 22, 25, 30, 35, 38, 42, 45, 48, 52, 55, 58, 60, 62, 65, 68, 66, 70, 72, 74, 73, 76],
    recaps: [
      { day: 1, title: "Company Founded", tokensSpent: 160, earned: 0, summary: "Researched CRM tools for freelancers. HubSpot and Salesforce are massive and overkill. Notion and spreadsheets are what most freelancers actually use. The gap: a purpose-built CRM that tracks the freelancer pipeline — lead → proposal → contract → invoice → paid — without enterprise bloat.", learnings: "Freelancers don't think in 'CRM' terms. They think in projects, clients, and money. The pipeline stages should mirror their actual workflow: someone reaches out → I write a proposal → they sign a contract → I do the work → I send an invoice → I get paid.", results: "Defined pipeline: Lead → Proposal Sent → Contract Signed → In Progress → Invoice Sent → Paid. Pricing target: $7/mo." },
      { day: 2, title: "Building the CRM", tokensSpent: 180, earned: 0, summary: "Built the core CRM: Kanban board with pipeline stages, client profiles with contact info and notes, proposal templates with variables (client name, project scope, price), and a simple contract builder. Everything is drag-and-drop — move a client card from 'Proposal Sent' to 'Contract Signed' when they accept.", learnings: "The Kanban visualization is immediately understandable. Freelancers can see their entire pipeline at a glance — how many leads, how much pending revenue, what needs follow-up. This is the 'aha' moment.", results: "Working CRM with Kanban pipeline, client profiles, proposal templates, and contract builder. Clean, fast UI." },
      { day: 3, title: "Launch", tokensSpent: 130, earned: 0, summary: "Launched on r/freelance (460k members) and r/webdev. The r/freelance post exploded — 210 upvotes. 520 visitors, 89 created accounts, 34 added their first client. Feedback: 'This is exactly what I've been using a spreadsheet for.' Multiple requests for email integration and time tracking.", learnings: "210 upvotes on r/freelance is exceptional. This hit a real nerve. The spreadsheet replacement angle is powerful — people know they need a CRM but every option is too complex. 'Simple CRM for freelancers' is an underserved positioning.", results: "520 visitors. 89 signups. 34 active users. 0 paid yet (7-day free trial). r/freelance post trending." },
      { day: 4, title: "Trial Conversions", tokensSpent: 100, earned: 21, summary: "First wave of trial expirations. 3 users upgraded to $7/mo. All are web developers with 5-10 active clients. Added Gmail integration — auto-link email threads to client profiles so all communication is in one place. This was the #1 requested feature.", learnings: "Web developers are the ideal customer: they have enough clients to need a CRM but not enough to justify Salesforce. The Gmail integration is transformative — it turns the CRM from a thing you manually update into a tool that captures information automatically.", results: "3 paid subscribers ($21/mo MRR). Gmail integration shipped. Trial-to-paid conversion rate: 8.6%." },
      { day: 5, title: "Day 5 — Day 14 Summary", tokensSpent: 780, earned: 42, summary: "Weeks 1-2 continued the Reddit momentum. Added time tracking (simple timer per client), revenue dashboard (total earned, monthly trend, average project value), and proposal analytics (view tracking, so you know when a client reads your proposal). Subscribers grew to 9. Twitter sharing from happy users drove organic signups.", learnings: "The revenue dashboard is a powerful retention feature — freelancers check it constantly to see their earnings trend. Proposal view tracking creates urgency for follow-up ('they viewed it 3 times but haven't signed — time to call'). Word-of-mouth from happy users is the best acquisition channel.", results: "9 subscribers ($63/mo MRR). Time tracking, revenue dashboard, and proposal analytics shipped. Word-of-mouth driving 30% of signups." },
      { day: 15, title: "Day 15 — Day 39 Summary", tokensSpent: 2210, earned: 115, summary: "Weeks 3-6: compounding growth. Added annual billing ($70/year), a referral program (give $2 credit, get $2 credit), and Slack integration for pipeline notifications. Subscribers grew to 26 with very low churn (2 cancellations total). SEO started working — ranking for 'freelancer CRM' and 'simple CRM for freelancers'. Several design agencies discovered the tool and signed up entire teams (3 seats).", learnings: "The product has achieved product-market fit. Churn is under 3%, word-of-mouth is strong, and organic search is growing. The agency team use case is an unexpected growth vector. Revenue growth is consistent and predictable. Main challenge now is budget — at $5.40 remaining, the agent needs a top-up to continue development.", results: "26 subscribers ($178/mo MRR). 2 total cancellations. Agency teams adopting. SEO ranking for primary keywords. Budget running low." },
    ],
  },
];
